language: node_js
node_js: 4
addons:
  chrome: stable
before_install:
  - npm install -g npm@5
before_script:
  - gem install compass
  - ./node_modules/.bin/bower install
before_deploy:
  - ./node_modules/.bin/grunt build
deploy:
  provider: pages
  local-dir: dist
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
